### ISSUE TITLE
Add probot-app topic

### ISSUE THREAD

**Issue by bkeepers** [Stargator/probot-arborist#2]
We're changing some of the terminology in Probot in https://github.com/probot/probot/pull/210. If you add the `probot-app` topic to this repository, it will show up in the [list of probot apps](https://github.com/search?q=topic%3Aprobot-app&type=Repositories).

Thanks for using Probot, and let us know if you have any [feedback](https://github.com/probot/friction)!

**Comment by Stargator** [comment]
Done
